replicaCount: 1
image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  port: 1883
persistence:
  enabled: true
  storageClassName: longhorn
  accessMode: ReadWriteOnce
  size: 100Mi
resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: "500m"
    memory: 512Mi
