persistence:
  enabled: true
  storageClassName: longhorn
  accessMode: ReadWriteOnce
  size: 16Gi
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "2048M"
  tls:
    - secretName: wildcard-blinkies.io-tls
      hosts:
        - registry.blinkies.io
  hosts:
    - registry.blinkies.io
  paths:
    - /
