immich:
  persistence:
    library:
      existingClaim: photos-nfs-pvc
server:
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
postgresql:
  enabled: true
redis:
  enabled: true
