service:
  ui:
    type: ClusterIP
    port: 80
    targetPort: 8000
defaultSettings:
  backupTarget: "s3://riposte-lance-mantrap-thrift@us-west-1/"
  backupTargetCredentialSecret: "aws-backup-secret"
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  nodeDrainPolicy: "always-allow"
