service:
  ui:
    type: ClusterIP
    port: 8000
defaultSettings:
  backupTarget: "s3://riposte-lance-mantrap-thrift@us-west-1/"
  backupTargetCredentialSecret: "aws-backup-secret"
  backupTargetPollInterval: "5m"
