service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx

persistence:
  config:
    enabled: true
    retain: true
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 1Gi
  media:
    enabled: true
    mountPath: /opt/recipes/mediafiles
    retain: true
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 1Gi
  static:
    enabled: true
    type: emptyDir
    mountPath: /opt/recipes/staticfiles
  django-js-reverse:
    enabled: true
    type: emptyDir
    mountPath: /opt/recipes/cookbook/static/django_js_reverse

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 8Gi
