apiVersion: v1
kind: ConfigMap
metadata:
  name: appdaemon-config
data:
  appdaemon.yaml: |
    appdaemon:
      latitude: {{ .Values.latitude }}
      longitude: {{ .Values.longitude }}
      elevation: {{ .Values.elevation }}
      time_zone: "{{ .Values.timezone }}"
      cert_verify: True
      plugins:
        HASS:
          type: hass
          ha_url: "{{ .Values.homeassistant.url }}"
          token: "{{ .Values.homeassistant.token }}"
          cert_verify: True
    http:
      url: http://0.0.0.0:5050
    admin:
    api:
    hadashboard:

---
# TODO: decide if this should keep pulling in the app files
# via a configmap. AppDaemon will reload apps on change, so
# a kubectl cp might be easier, especially if subdirectors
# start getting created.
apiVersion: v1
kind: ConfigMap
metadata:
  name: appdaemon-apps
data:
  {{- range $path, $fileContents := .Files.Glob "config-directory/apps/**" }}
  {{ base $path }}: |
    {{- tpl (toString $fileContents) $ | nindent 4 }}
  {{- end }}
