apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  appdaemon.yaml: |
    appdaemon:
      latitude: {{ .Values.latitude }}
      longitude: {{ .Values.longitude }}
      elevation: {{ .Values.elevation }}
      time_zone: "{{ .Values.timezone }}"
      cert_verify: True
      plugins:
        HASS:
          type: hass
          ha_url: "{{ .Values.homeassistant.url }}"
          token: "{{ .Values.homeassistant.token }}"
          cert_verify: False
    http:
      url: http://0.0.0.0:{{ .Values.container.port }}
    admin:
    api:
    hadashboard:

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-apps"
data:
  {{- range $path, $fileContents := .Files.Glob "config-directory/apps/**" }}
  {{ base $path }}: |
    {{- tpl (toString $fileContents) $ | nindent 4 }}
  {{- end }}
