{{ if .Values.homeassistant.token }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdaemon
  labels:
    app: appdaemon
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: appdaemon
  template:
    metadata:
      labels:
        app: appdaemon
      annotations:
        # TODO: check on the best practices for pod restart on config map
        # changes as it doesn't seem to happen by default.
        #
        # this triggers a pod resstart for values that are passed into the
        # config map. It will not trigger a restart if the configmap changes
        # structure.
        values-hash: {{ .Values | toJson | sha256sum }}
        checksum/apps: {{ (.Files.Glob "config-directory/apps/**").AsConfig | sha256sum }}
    spec:
      containers:
        - name: appdaemon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          ports:
            - containerPort: 5050
          volumeMounts:
            - name: apps-volume
              mountPath: /conf/apps
            - name: config-volume
              mountPath: /conf/appdaemon.yaml
              subPath: appdaemon.yaml
            - name: persistent-storage
              mountPath: /conf
      volumes:
        - name: apps-volume
          configMap:
            name: appdaemon-apps
        - name: config-volume
          configMap:
            name: appdaemon-config
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: appdaemon-pvc
{{ end }}
