{{ if .Values.homeassistant.token }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
      annotations:
        checksum/apps: {{ (.Files.Glob "config-directory/apps/**").AsConfig | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: TZ
              value: {{ .Values.time_zone }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - name: apps-volume
              mountPath: /conf/apps
            - name: config-volume
              mountPath: /conf/appdaemon.yaml
              subPath: appdaemon.yaml
            - name: persistent-storage
              mountPath: /conf
      volumes:
        - name: apps-volume
          configMap:
            name: "{{ .Chart.Name }}-apps"
        - name: config-volume
          configMap:
            name: "{{ .Chart.Name }}-config"
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: appdaemon-pvc
            claimName: "{{ .Chart.Name }}-pvc"
{{ end }}
