repositories:
  - name: longhorn
    url: https://charts.longhorn.io

  - name: metallb
    url: https://metallb.github.io/metallb

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  #
  # Longhorn
  #
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.5.3
    values:
      - service:
          ui:
            type: LoadBalancer
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          - "patch"
          - "storageclass"
          - "local-path"
          - "-p"
          - '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'

  #
  # metallb
  #
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.13.12

    # TODO: this seems so janky. this can't really be the best practice, is it?
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "sh"
        args:
          - "-c"
          - |
            kubectl wait --for=condition=available --timeout=60s deployment/metallb-controller -n metallb-system
            kubectl apply -f metallb-addresspool.yaml

  #
  # prometheus
  #
  # see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
  # for cleanup
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 54.1.0
    values:
      - grafana:
          service:
            type: LoadBalancer

  #
  # home-assistant
  #
  - name: home-assistant
    namespace: home-assistant
    chart: ./charts/home-assistant
    version: 1.0.0
    values:
      - image:
          repository: homeassistant/home-assistant
          tag: stable
        service:
          type: LoadBalancer
          port: 8123
