repositories:
  - name: longhorn
    url: https://charts.longhorn.io

  - name: metallb
    url: https://metallb.github.io/metallb

releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.5.3
    values:
      - service:
          ui:
            type: LoadBalancer

  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.13.12

    # TODO: this seems so janky. this can't really be the best practice, is it?
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "sh"
        args:
          - "-c"
          - |
            kubectl wait --for=condition=available --timeout=60s deployment/metallb-controller -n metallb-system
            kubectl apply -f metallb-addresspool.yaml
