bedroom_button:
  module: bedroom-button
  class: BedroomButton

goodnight:
  module: goodnight
  class: Goodnight

light_group_all:
  module: light-group
  class: LightGroupAll

string_light_follows_path:
  module: follower-light
  class: FollowerLight
  leader: light.exterior_pathway_lights
  follower: light.string_lights

lamps_follow_dining_room_on:
  module: follower-light
  class: FollowerLight
  leader: light.dining_room_chandelier
  follower: light.common_lights
  ignore_off: True

# kitchen_motion_light:
#   module: motion-light
#   class: MotionLight
#   entity: light.kitchen_ceiling_lights
#   night_mode_entity: scene.kitchen_night
#   sensors: [binary_sensor.entry_occupancy, binary_sensor.kitchen_occupancy]
#   delay_sec: 900 # 15m

office_shades:
  module: office-shades
  class: OfficeShades
  button: sensor.office_button_action
  shades: [cover.office_left_blind, cover.office_right_blind]

tv_time:
  module: tv-time
  class: TvTime
  scene_playing: scene.tv_time_playing
  scene_paused: scene.tv_time_paused
  media_players: [media_player.lg_tv, media_player.living_room_atv]

tv_time_button:
  module: tv-time-button
  class: TvTimeButton
