goodnight:
  module: goodnight
  class: Goodnight

light_group_all:
  module: light-group
  class: LightGroupAll

motion_light:
  module: motion-light
  class: MotionLight
  entity: input_boolean.fake_light
  night_mode_entity: input_boolean.fake_night_light
  sensors: [input_boolean.fake_motion]

kitchen_motion_light:
  module: motion-light
  class: MotionLight
  entity: light.kitchen_ceiling_lights
  night_mode_entity: scene.kitchen_night
  sensors: [binary_sensor.kitchen_motion_occupancy]
