keys:
  - &pbozeman-dev age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
  - &pbozeman-mba age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
creation_rules:
  - path_regex: helmfile/secrets/*
    key_groups:
      - age:
          - *pbozeman-dev
          - *pbozeman-mba
  - path_regex: terraform/secret.tfvars
    key_groups:
      - age:
          - *pbozeman-dev
          - *pbozeman-mba
