apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-nfs-pv
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /storage/photos
    server: nas-01
  persistentVolumeReclaimPolicy: Retain
