apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-nfs-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: photos-nfs-pv
  storageClassName: ""
