homeassistant:
    token: ENC[AES256_GCM,data:+sHpDDuQVBmjt9l82PexP3QJNAYNuaH7DmG/GNEcGDLtox5VExsCeQUOWydh8qP5ZjPyI8JqKJCpiglEtBOQWsTXPZdcEZLLYV2w1vGC0kVBd2HHO/lFCRgKTgeVRDqh49JCwCFU/cRXZAf4B4vdsTl37nqLhPvDf4i0WF4viKVTuCcpNHhRm3di0JRkcN2IpSnhD1BGgBZLFc7jnkcm/PjlKHtGo5hLpLT/v4hW3Humfrb4azpp,iv:ioPFSv773ORNR9pC/6ImDXxgKGBGqmdThDrLumu2PxI=,tag:anIhxMqMQcmvxhTjyQq8LQ==,type:str]
latitude: ENC[AES256_GCM,data:d/wC9ug=,iv:YPMStQic4NoY7eVd0OQoQM5vvEbcyIw+zhpnmIW5ChA=,tag:MYizD0q9QUVJasjUoTqwyA==,type:float]
longitude: ENC[AES256_GCM,data:MAwfSekaAA==,iv:jX9XhYrWktTn7vnOqPFeBq5ia228CCenK1/l0DRWPqY=,tag:GMXbcqt+4ewWWlVKy/DeVQ==,type:float]
elevation: ENC[AES256_GCM,data:sc3Y,iv:G04TzvE0qAOSh/Fx1ZM8SXOhaz0gd+mBqNd70JJu7XE=,tag:L3Rv3jD7c0o1BPAobOWh7w==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWFVibFhaMFBKM2E5STBq
            akx1WUw0dmdnd3czWWpHQ2hvYWUwYlQwdXgwCmV0cnE0Rm9hT0hpcXhlU01tWEZi
            dCtLT1FvTE96WmVnTENFQ3FWRkplUXMKLS0tIEVvQzIyZVI0VzgwajVFNlpXYjhi
            RnduRThzTlMwZW95OHpReFd5WnJhaUkKBwioosRu1iD7G34thJGzeHF3IRAooFGp
            9ZYgO23g+o4qKglLxB6+jGVuRizQ7zr72vwARAB4c3fI2hJ5I09uMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcXRycHpvdGpuMkp4aTRj
            WEJhZks4aXU4OHF5d1lBTERrcEJjUnpTRlR3Cld5dlBXc0J0Ymh4YlZvV2RYUGN1
            c3pBMTk2OE5xREJRU01KSmRHVnMvbTgKLS0tIDdObCs5bTFFTzRnN2lSTWVveE81
            OVVFSmF5OHNKL2QxMDBORDgxb1ZidEkKfR3Gnj/lIK5Q4bLXXLu+tL4HHZE3/dUr
            ruwv30MtdwgV7SS7YxVI+gKEeGBC4/Z6CEzR8XtJuAtKwHDV+OV1Aw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8tzahcl0gfugsz2earwar3ga2rtqlgm9lrpc790ju06gzs633rqgn0366
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZERxbmsvTXYzRTZ5T1ls
            YlRMQituNURjVUlxNndHYUdpNFdUZ2t6VFh3Ck5BaFVFdFNMaCtDY3QrbzliUXBM
            aU1yaUYxcWpmWGZtWHZUbXhhYXlBdEkKLS0tIHdIRENzTFZWZ0lrdFRQblpOWUdz
            OHRqelZSTUhXUVdFeVpISzJmM255ZncKMXxwPPKRLpBuODkX4boXJCNOFFxgUMDX
            bNTc6IEKu1VJEEL0xLaHEzQvbB3tcG+s6WRSQ4DbbXtn2/cuYp+fAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12rh8n3qgq5k9jwwhhvrpmh4daahtjh3q28nm4pn5rwryvr4spg4qmadxxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaU5zR21vbWlOa0FRNXFm
            RVQxV0FURk5ZWkJWeWxWdHgvQkxobURMVkJFCkw5N1dITnk3NHdlN2FibzJOM3dE
            akk2UysvcFJ5TjhpaTRVUmYveXM1d2cKLS0tIFU0dTFKSVlXRUZqUmxtTEY3clEw
            bnBIbUU3alkwVWpiQVZPMTVOV0JDb2sKAU43q+OUxY79dHURiM9QUJmfSTmDX+YL
            AA7kxHWelNDfeUVKmxUEEPqQn6e7Tc/46RufM0lqO7U9m+ME2LaU2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T03:02:21Z"
    mac: ENC[AES256_GCM,data:330eTeXzRsGdoJpwc9pHjwQQk8nWYk7wi3youTIZkeM7euOd23jNcGhqwXUf/m2+1xCeBuWTGTVcJpbGDPx8GvDcr79mRkJSGxV3XvF5TQgTqBK6TnfkqBbdnCfdU5sXLbGU3LaDP+H3xa9Q5Z82ZvUg+Cfh2mAAz3s6FQJzf/4=,iv:xOf8kB4D4dROxNnHwvANtLQOCTsmP8jYijgaMzbDmX8=,tag:bKqbiMCfhFlWNOd38on4gw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
