homeassistant:
    token: ENC[AES256_GCM,data:WJe9SsSVkl30vp5kD9ATcQp6MeWFk47mOwbFRS+qbZwAxCkZo+kqOtmfIlCvrCPVZTO6UFf+1S1qUu+sWP5ruiii5fAmidTa81hPieKyKHx+lHHbjrGR0J/3v2iR3KNYBoXELYxpqTd5XzOhmum1uAy6CsXcvAFRugo9PJMQY+m5B8FWvJZ70iBKWuMMilcRFN23tIQQLMifr02sn5vxZEKNNKH46Q7MezO8W4cQwWEVOplr9QMG,iv:f/72TlhQE80mMGvlKrM+VfEocW1n5TxemkC/dsTY4M4=,tag:8zq/jedHDrfytmjj9Ybm/Q==,type:str]
latitude: ENC[AES256_GCM,data:0UdNYuE=,iv:mkkQQnJos1JbZEA0PWYZXDMNOABD36v9va4Gx3OrSVM=,tag:gILwUbUwLktmWghS/DqJbw==,type:float]
longitude: ENC[AES256_GCM,data:F07Ldj/+,iv:hlDIVAwLfcYRCTuTCCuELfLFtsUJdYPoTDvOPF2y3jU=,tag:9IAiNPlk7TXh3yiC44ZMHQ==,type:float]
elevation: ENC[AES256_GCM,data:yFgk,iv:mhN/p8BjMYEzHOAzaMZWl7YR/uWRQe9XOIgZD5Xm2A8=,tag:QoX/yAsr6Qar8SpYnTxKZw==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbnJoSDNraXdiSHlTNXIx
            b2ZZbGN3RXdLR0l5c1F3YTdJaUpxMi9Pdm5vClZzZWt5ZTR4Y25XcmRmWFRYQjkv
            TytLb010dGFNSjJtalk1U3pzdElWQmMKLS0tIG81eW96L3plOHlJMHU0SDhTZ1pa
            bFNrMjFSUnpEbU4vMFI3VkY2YVpXdjAKuyiJ82tHHxHKdpq+J9vyGJj4ySs7gGxm
            K8uwvkfcrkIpaoKBo+j5ENRs0n7xpaMXlXU83A6EsLLpnYt2zqcTIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTnJRSGtNZXBVd2ZZZFpY
            MHRTVm9LZVVrUnhkc1BLU2JMNEVvNVZTNTBNCkVWZXlXcmQvcGUvMTI4Wi9yaFNw
            YmtkTXNYNmxxUEI5eFJQREZLaFRwQkUKLS0tIGtuNk4zREo3ZjJERWl3VlUxZ3h6
            ZWZFL0d6UGhXRytRZ2lRVHpkanF4QTgKXSTrAYrPEmNbRZkQSRffJgyqOQgLuWMf
            +AnyVHHuy9C9pcF1uEvbP1zDqMf96gvxWUFXDB0UZeKHPyeGTisb2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T03:24:43Z"
    mac: ENC[AES256_GCM,data:eQyZuRxHDzmxUtF1cXe15xUwYQvt3Tc03fcIGUP/ym7P2kZ7t2JUIGit9dxMtJNxwLt3zxLECIuG3x3RBQl0A5V0jzUgsstsiwMNn8twA/T6R+VJb+bChwT8b6FhhLBk7bIPsSS5GRh8UWzjgr+76INePHvzjGAHYrUVRe5R3j0=,iv:FJBvuUbgCuP32GAqM7Szi678iDtB9N/GpAoaXllx8VQ=,tag:ZVztFnyG7REDzVx6jbNCag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
