#ENC[AES256_GCM,data:L654MKXDC0wqPxeAxQfui0RTl3+JmK3/HrRZ0J3vtHjbnqbqf9ERozxlBObTz9tb2I+f,iv:hkUoYyRRYwwfiwnU4t9fW4UiW4sC63/SRvrHuzVQdcs=,tag:/K7CCKADODhSoZm1xojcZA==,type:comment]
api_token: ENC[AES256_GCM,data:e54AvB36cilQcwjRgPAGhTMjfKSNLGjkOeGgkZx0RCNKfM0yGwSIBA==,iv:tpLMoWiOa5wmhNbPIXqnnL4f/RWJcdjAEodh5Z5lXwQ=,tag:JqZONtmgOEM/48uk3C9UPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdEJVY1lpVS9TT3JOWDZj
            TjdTeW9YZEUrN0oyc1Y3MUhmWTJ6a1RnMkFZClkvVXZ1R3JGNHJwUGZITWhrQjFE
            bGJTdnNMbTJWdnBMaWhBR29IRVZjTDAKLS0tIE9LZGMwbEppRXFuNm9aaVlGUUNl
            Wlg3cEVYdVdMQm5RYkJ5aURDTytYRlUKGkmUlDSi9p7lJPFmJY4aJRfnhBcLHFfp
            UOZvffEZb7Ei5mpVw86A48JqtUXCbUokfcOlLelRqSJKBONRyRx5Dg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d0hURXI2RE51dS9KbFA4
            RzBncTJpLzdNWG1QQi9RWmZNMzRaS29SVVVBCm9kOHZFTWRsb2orekdkNU9NZG9G
            WmZNem1XNEFCN1FLWDdwYXFOSmw0ZUkKLS0tIHZsL1hDNTRvTzNGVUJmck13dkxF
            U0xRdUR3QlcxeE12cVVRMkdxRlNiL3MKlX87R5XXCxwtnDzgvMhHzfcie8KneJvm
            IXIjiRRJm6oKRDsbbnlquJxQCyecT56e3SY3BkXlKkt9ELU9BLXMAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8tzahcl0gfugsz2earwar3ga2rtqlgm9lrpc790ju06gzs633rqgn0366
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzM3NEUmJwWHpzV0EwUXQ5
            dUFXSS9WekdiL0xaaUtGeVFOZEZTZWZTYzEwCnZxWnhQNE9ZNUFwVWxFYldHYnZ4
            ZGE5YVZ5WTFHU0VydkI4akZ3bnEyVmsKLS0tIEZJTzFUUkpkNC81OHNpcEc3ZGFH
            NDRWZzNhUEpNV1lUekVtYk9zVzUvS2sKD/pYL4f3pM4aEF8DbOZiv+Sm+ErvEqg2
            E6mvibHzNYxHVKX0bYyEXxIwgRsFpBtNSJ+WvNY3QwUYrif5qlTe6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12rh8n3qgq5k9jwwhhvrpmh4daahtjh3q28nm4pn5rwryvr4spg4qmadxxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbkQyVWZyY21rR2taTVY2
            ZTJ3d1NvUnJBbWsxQzdlMm54eXFjTlNxcmlzClpYWHdQRDBKVWQ0REhvSzhtQ3JW
            V2JnSXo4K2I5ZWFpTkxZNll3ZXdXRjgKLS0tIDY5cDBOQ2VSSktRSWw5VStZSkJi
            TXBDaU1LVUlrVXEwMURkdm1DanVzbEkKJL4y7Eab0/gWJBLoYA9QipiY5Ni83ntk
            mWdjXWJG7J6fzJLd0TI0DXnloQ93uEK6wGbydz5v2gnIa16ilv15xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T03:02:21Z"
    mac: ENC[AES256_GCM,data:+5m6UhoqxNYXrS6yV063dVe2UI/iY8r21E7i4GXnZ6XGpNefQUS+ou2ypygqzuHP+IBTw0KZju7PShfjzlTzP1vRtbi+hsnFqi6Pyv1/DZdnHNoHy2H+ZzWrKeaDu823c1M41Tbf/hYzbRXp7XC0/t9GnTZS3wM8b4vZyOP3Vmw=,iv:5wSXytaN8eL7q26GcuH5LnANh6qQGdGI+fmBWqLaBc4=,tag:L5yLkTAj+/P+G9AS04ojrQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
