domainname: ENC[AES256_GCM,data:+axO9PPvduek6pY=,iv:A3ckt+9F0YRtxwwGuh4w80UA6Jnz8+tGmWy9T0HHiKk=,tag:P/yOzzHVDVwKsdgi7yFBHg==,type:str]
email: ENC[AES256_GCM,data:u4IbhNAK3djopSov/JcVQWhf,iv:yQOzvfdIFb7V3Cdcwe/ywMQ/2iCiUnzE7sOvt5wvlPs=,tag:SLWrnAbHx1FY5lnadDoKKg==,type:str]
latitude: ENC[AES256_GCM,data:EI5L1BYHDZjF1BedoOvSGbY=,iv:dsKfY6OrDmJFb51ECG+GUhUA6/FvjO9SAxWK0smj/6g=,tag:TEBGDQ67Ofh3JzWtMtkthw==,type:float]
longitude: ENC[AES256_GCM,data:vvRQHiy3p9I01Sykcn9QS741Dg==,iv:D24GXKwgPH43rmMGBI3H1j1z9C7KdOH3iFr6er0f1OI=,tag:9ebK+/VWgwjyxz/XeVTwkg==,type:float]
elevation: ENC[AES256_GCM,data:ZWFL,iv:yLNoplQ03xFVQOObQL0wXYzoTk8vMpd1H+eh1B5NXcU=,tag:gkKBzRmY34ZF1X6SC0xRyw==,type:int]
time_zone: ENC[AES256_GCM,data:806meicWhaqlZFpzMyoPrUlk0g==,iv:WmmS7dzQNU9Yiut1FvwgS7SGIU1p3ZuYU6B89Zc+/7c=,tag:T5aVgjWUFIZpmiAJEmH8sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWG9sRDlhdHdzaTljZTNk
            Q1V0ZXRHSnBCdHNoVVZraGVGNldZMmpTY0FRClNVNWdmeHZ6dFh6NGtGM0tXODZx
            QS9wS05mcVZGN2FEbGloUFdwaVcxL2cKLS0tIC9JWUcvOS84RlF0bXlYUGRNeUw0
            eGtuMXEwQmpGTm9xMGJNcENWZ0VFN2cKfJBquQ/fIQtWRtEClMoUpnBYXoVvwLu8
            1jAqS0gPP/mVjisvZw4aUX3W3CzViWYG3xVbJDhN3IZEe4wVJAH6xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVGtjZFlRUkNTcEJHdmVy
            bElmQnI1azdTQ3pWMzJiOUVOOWNyT2tFUFNnClN4cFV6UDhLN1prMXlCUzlFamxF
            ZkIwa1I4MlhrQWFqQjVNN1h0d3BLUUUKLS0tIHRNbCtob1J3QWtJTG5IN1g0ekdR
            dzE2dnhPRUE5Z0h1NzNOemF5Y0p2WG8KSw3FNyrxtSAWOxSDXbiQiVoTlZSEWpir
            QlEoBXF2D2cHsLm/hqUAk2QSdwu0Xdyav6rnS4evXCR4VxWo6hxU6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8tzahcl0gfugsz2earwar3ga2rtqlgm9lrpc790ju06gzs633rqgn0366
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOE16UGdDUEVCcTRXSm1Z
            RnpvWTB5WlZSTGJoZkZXK0gvY1ZFUkYzUmh3Ckk1cFhTUzdhQWp2QWJPbmtVMTlH
            Z0NieVVNQjB0eGdXL0gxaVJ0eEN5aE0KLS0tIFhJVDBBcjN1UlFHaGowODJRaXVm
            czFuM3RXakZZUHJ5ZkVBWXRYTFVYVVkKA4l6uheeK2nM4QZ7Y8lXSoibwEbK4Xcc
            2YQAdWZCGcsIIVVQgXgxaBTNSUO0FhiYvYvf/qOCP9kQJznwAMrIPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T04:33:27Z"
    mac: ENC[AES256_GCM,data:21kA9kwaOJgsMSa9ME4JrJ3e8zv9pUC28TX1VAwJoFhLikDzCrs9w5emGss5Tq1FNTXyDa2CKgc4RktWfE9TMrvREIqSCqx/rdQKMDOoUNDZRNmsyD6lu3qUSGUMbZ1p6WWbiWb2gtfCqKv7qgleYwbV6d72NpQZacVjo3ujsQ0=,iv:9Ugra7ev+UeI/mzf0zfY23mjQn6tLgrm//faEWtaHcI=,tag:xz2kLALHBv+RRAYsqEQDzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
