domainname: ENC[AES256_GCM,data:nnW7pqQ6b4hOj6g=,iv:EvhNFkaPQO2GFyziHj30lUEfCVArF2ElXkJQwWeF/dM=,tag:pJS2j965gZ5mF5UaaKxA5w==,type:str]
email: ENC[AES256_GCM,data:7TtZMRsThraTeJgM9/O2/UN0,iv:+I3Uvh7t1Uu0Xm8R5n+CTZo6LmN+ePjucvGjMNs7NFg=,tag:q8520zeP6dQDw/Nks71j9Q==,type:str]
latitude: ENC[AES256_GCM,data:d6bUTCP9vu57B7q9Qg74tlM=,iv:kSpWJ/KgYsm3UL/tpENX9Mj9WqOp80n4Pn7XtPrFhG0=,tag:kxn8jbfmj0A28rOeug6g6A==,type:float]
longitude: ENC[AES256_GCM,data:Q6swhdsbZzGknWi00wrNGdMFGQ==,iv:RDYR7hjrdkIHfgEy2mOU+9bGyqt4bFP74AirZI8vHv4=,tag:Z4l6fzmwZ1ZsKu78e4x0Gg==,type:float]
elevation: ENC[AES256_GCM,data:Pd4U,iv:KOi3WpsYzL0uXBH77rtqJVFnNGGpn8npndXDC/tOixg=,tag:U/LCaFQsIddJKWG6jYDZSg==,type:int]
time_zone: ENC[AES256_GCM,data:QOdg4Jn90Ka21TgKX5wvmI9yYg==,iv:ELbWxVt83OLeiYtbKLBYHPHaCWJ320ti75K0Cd9Zvd0=,tag:SljR57NiTSopMHP8mD8Kqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTW8xUFc0dlZ1NDdIRW9k
            SVU3YSsxQ3Z0aEtaQjBMeEJmZmF4OXZqaGwwCkxKYWNOY1RYS3orZmpwQ1NRNEgx
            bWVQd29OOW9jcmZ5ZFBKM1ZVTHVyVVUKLS0tIFRQVVJDZVluOWx0UHpMZ2xsMmwr
            UmZWeGEwVWxvL09RV1RKTkg0TDZjSG8Kw03QetsMjyHDNtI87h6Yt+fzjDSin90i
            lYD8NNK+cbZOx5epfO9wqxzd7y0APEtnlIjg/SfvdFpWff4O+Yh7UQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M1M0bHhuK0t3OTFIR1Ex
            NWlZcFdrSDM4WTFkVWlaOGxhNmtNZDlsUFFrCnY2YzMrSVR3dmRCQ0Y2cG83bS9P
            aDNtMW5qZTBBbCs5aVE1WGQycHVwUWsKLS0tIGZSTUhaZEl2OFhYdDR1TE9SYlRa
            cjlaR0lNaUJuRENNWG1BRGJ6RFVSYlkKJKTUJ7/vCOLEJoLA9bDrf8E9d3dLSRoc
            cjtttpw64lLedwkWElEyjdx9IJCZucFsHAQhNFNDJ5bQAA5wqNCNWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8tzahcl0gfugsz2earwar3ga2rtqlgm9lrpc790ju06gzs633rqgn0366
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OEQ4b1RPU2RqL28wU2JW
            MWRwcjBqY0Q5cnFMK2xvcTk3L0xaM0F3Q3hBCndIQzhaOXAvcjNveEdrdUllZHNR
            aUY5N2NKVHgwazE5U0lQQVJ1bElLN00KLS0tIERpc1IyZXlROE94RHRSOWNDVnFt
            bXg0UVFLVERYbmtXQzk3S3FzTGRkOU0KMo2SDyiHrR/egg76IA7I/pXp53pm+HL+
            GYLjVcmvLM0Ce9848rrgow5mvqbRNmz5l+r+V3mmVL0n0ZPN3FQX2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12rh8n3qgq5k9jwwhhvrpmh4daahtjh3q28nm4pn5rwryvr4spg4qmadxxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNR1M4UldhNFpjNWtPc2lH
            YzFuMGcxcDYvWkdGa2llNk56V0tuY2hCd1ZNCkovMkRaUkRHVmw2QklHMTF3UXky
            aVFGbGtlMU02cDlLd3pHZUI0aUEzeXMKLS0tIGMrVlJZOVRPUnp0TlFzQ2RkSzF5
            QUZwWW1mTHFzY1NaaThQSTg1L2U0a3cKiwnliqB4PBBTYm4nN4r0uZmD5zou0U5e
            ArTKtyAEzUBpFvBU3ZJO34eSJsbbglxMJ4I6aoscF4BHqW+mxsj5JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T03:02:21Z"
    mac: ENC[AES256_GCM,data:Qfxy6Ral2yXMTlVzBEEYuZNAmdMb3I1h1R9+6xJ3rCh8o+AhcddLow5LWYwVnYhOf0AX2NsZHvq3OrZ0Sv2cFf3R9LGb6O+z2wuH0fb+jkQ0tAN9+njzZjz4w0HZ5v5UIpJDbI54mULlaS7J4t8NwUTfjOVVzcfAaUjtwq8tZto=,iv:uGet9IZ9mwl0PksS7b7vfmT5vpOM5Se+srgcQ+/dOws=,tag:qLtwV50FBXXtREW4AJoCMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
