password: ENC[AES256_GCM,data:zy0TvuEXFnQMDljUBwoyWN5tR8TM4hi2DWgTWgSYca4KyNuAmhi01pHumWNVyPg359E3mTWBm68OnOjDTYhpqQuDJhRqGQcAPcAWPEAJbDHE2NVVO/no5aMGxKEaFB8TFT4TewE+vuLX4gxaFygexvArrQYL,iv:Xx1Zf0UNTOmdU8j+664sGMWY2TqSCwfubBES5X5GaOs=,tag:1g5CLza5ximjMTuN8EByqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvc3dBcXd2UFdmUHFjTVJh
            YllSUWhZSzZxM1h0bVQvaDV3dHlhWDQyeFVvCnF1aktxSGlncmZHaC9xL2ZQS3BV
            U2M4MmZiRGhtWlZsSTdWb0JBalR1UHcKLS0tIDZCUUgvRW1SS1RKZFRKZmkxMEU0
            Yk5yNURuek9BTHF5UWwzRWtEWGp3U3cK2nHzdyDsGxaeUQRT2XdXDVrLNill6WG4
            SYEUkyF2BQL8QTPqtPK8t1GAvT4nVCsOxH9xqIYs2y70/A7JMnvAVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-27T01:03:27Z"
    mac: ENC[AES256_GCM,data:zGDy0OOFwYgehVIO9pEf57cCI2VVtXVJteXEWwXc+rt86xGSRXGvSA9plggwQe2STZ8Dp0TovbnWr/px/pGB7iwYgRgHOCpNlTsB9aoteZPEWDI7zL4DaY/YNy17Pqde5R3e1KxtwLWDG5DOQnbBfbRDWsLSvFzZbjURNQO6RaU=,iv:N9F9hHHPxwKinmL9eC54YxECnHgbM77Age/txL2JwQc=,tag:GeeNHkLGQhgijIdjtAKy3g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
