grafana:
    adminPassword: ENC[AES256_GCM,data:SUXaY46WAgH5,iv:cvYf+2/XCynfZy3CEgQ3PBlsbS/7JBSi2aBENqwCODQ=,tag:2vXV1LvOlOYxG5KVP5YFZw==,type:str]
    ingress:
        tls:
            - hosts:
                - ENC[AES256_GCM,data:dobsGjcc6uLGMPfiNgDtP6zjbA==,iv:URtmNArVJSUCh0OokoWDNn7OLLIvwUXKwsy90/zr0Wc=,tag:JHu7o2XpBLMS4d6CLv2AGw==,type:str]
        hosts:
            - ENC[AES256_GCM,data:SPSu9ZxSyM4jhPrW3kXFXSpK+A==,iv:Q7DTuBj2tkwqvDQBqZnM+MxHL811Y14eam1WiABl0Ug=,tag:+VrDGLiQ3bZz706tObXx9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSHlFb3Z2eGZkdEtTSDlE
            MDhZU2hoVXBlMG9Uck5ZWWc3YVoraWV1c0JZCk5RaXloUkhXcFB0TDk0NUJaTS93
            NGdjb25RdTBUUG1pV1ZlRnFneWoza0UKLS0tIGJGQWpEVnBsdGFnY3NRZ2g4ZkVu
            RUIrY1NwY1JXekttRVZLZkFSNitZejAKf5b1sHGeoootuQQxHBckgCnlvNFtdnLK
            wObI+TbYrW1huWcexMqpvuZJ46QPYRDPmtKu1xQhZ8JBIfyJOwaEGQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eDMySGgxY2RoL1NhQ2xG
            N1F2RDhXY0UrclVJVmFoS2lGbEQzUmJlREdrCklySVo2MkFHbHBxUkY1TEdJMGVC
            SmJnbmhWaTJMWXg2Q3NKVlBxajNLTWMKLS0tIHRGSGlRaHRiMkxSeDFvcEFmRmFR
            YmRNS0VVVGlFSGFsSGMxbXVhdGdPU1kKlVJo4pkJZMPlNglsQrHQfA7XnAE5WPwS
            jUdjaKGqSyimHiE0Z0jPbYDQpYChZzOoIVt2YqSb1JZOdCquR3mTaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8tzahcl0gfugsz2earwar3ga2rtqlgm9lrpc790ju06gzs633rqgn0366
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYTg4R3puRmFpeG02eEpQ
            QjZKUXg1ZHJXVVBKZUhpZDBJSzJ4YTRXVnpzCmdyTG1lL3QwYXZtVExDdVNQeGR2
            Mng4M250WHp4MG1tQ25GS21IMzg4dFkKLS0tIGJaakpaelBqYzEzZDJyVU5PWk42
            VUk1d2hIZm91TGdUQ1BKazU1QjhVS0UKHxipab+lmYTNEcNzzZCnOLitaAnox8lW
            wWbTpH3UI2M3i7IPvRywGV/6VAVViJsAu4OaZFWSUbOMM44zx4wIYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12rh8n3qgq5k9jwwhhvrpmh4daahtjh3q28nm4pn5rwryvr4spg4qmadxxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSXZwODJFNCs5cmgvdHVQ
            dmVWUFBSZEp2dTc4NzhJL2ZobzQ5QWtnNWhZCndnNjh5U0ovSkpYRXg5dEJab3gx
            aHN4VnJSZjB6amFJeXpKaENUU1Q4UlkKLS0tIHlkdENKQnh4emVZbEtNR0FRbVEv
            eXMwY0lZTlFHTG1KYnRUdTRzcC8zaXcKDkQ5epwFLpRzXaRYaC1iEcKv5Gbx36zt
            NLYpidXlI0nfrRBxa6gMm9bvQX3PkpjSU5WmNQWy1tDUGttz4Apq6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T03:02:21Z"
    mac: ENC[AES256_GCM,data:6tRSMipdUFxPJvWOaQqEHX1GlqB3nbG74NrzKKlrG+284zkBWe2Cg2DeuX3R1ZEfQ1yQsdJ1IAKljzCqF8d9y1D0rWfPRsI3UCSX6LWzD8z3qwRRtYuTPPCz2GaFbBKTZa2tOKhSGgFDNW844DONjFaCPTjIn4Qw9IBLR3IdiYI=,iv:rywttsZxyAUwJhaC/vrWmtNdKat5wmHHCB/Ynxh0u58=,tag:uc2HS9o016TTxFzAvQCpSg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
