env:
    pveAuthType: ENC[AES256_GCM,data:dTdW8Bcn8vI=,iv:N9FqVGs+kbxq0XNl5zUW1WkrSepAVGvXnYjcHTGKNVc=,tag:ovNYXx5OV4/CluReaq1r5A==,type:str]
    pvePassword: ENC[AES256_GCM,data:10HD1W6I3mGKpyU5xqIk6MCSBsNHt79b,iv:jqHzU80c3+6KK1yO2xsp3zGsn5KHukFYagEa8jFsrQE=,tag:pG1KtAPIR7UPKGesh72C0w==,type:str]
    pveUser: ENC[AES256_GCM,data:TcD0FBi9BkGOObgOPuA=,iv:5elqcgsYJFOeZb80/1mces9Ns1VBkBOXROlDaChILZY=,tag:pifXXOqJ92EZhxmxPEmcBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMzhqNjJuN0FXTVBVZmNl
            U3JhZFhuSkpDV0wyaVRJSTdHRmczSXBudWdvCi96aHF3VDJlSTkvemdVbTV4cGxv
            aWVVenBOT1BNOFplandtMkJZUUVrZU0KLS0tIENTOTdZSjVJemduOUd1dlZia1pZ
            UE5kU3dSZFRKYUVuR2ZkU2htVE5ySWMKpwKJlf4ovzlOtjvLYKOeOiZ2ytF9hTs2
            Q/GVCTBr2Mtv+ZiwWmOdnJwFHjv6jgxM7jHfjru7d+pTYfP8zIKZYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaV0owUDJmZFN3YzZITThU
            ZjhtaStmZnUzR3N2d1c3WDBuQWNDdnI3NUgwCnYvUjk1ZmRYNzBDSWkrenBlSDZo
            NWhFTFN3dFZiSWRiQ3NhVysyTzRRWGMKLS0tIHZscW9VUUNsU0QrcXlQSEdqOXJG
            TjlpZ05DNnlsNlpvdzBHY2JVaWdNTXMKDhwYu4WPSrtmhdDtMp6+Te4wQ+PL/Ud8
            n2fseq9x1QqU6aEGM7oCXnPrB083aOcJFup3XLalfsAF6bEWXS5FDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T02:53:45Z"
    mac: ENC[AES256_GCM,data:1oy9a0VBh/zjwxsghVWDFmyBulp6rz4m2KA9st6LvGVPS+rCxvo+xKK57tQW2kOVwZxZBDUVDc4Q/lAnDStC1srEHB/0UIzhLvfF1S3KKfwpi7qeh7ITcqFnHTNQY8D4FpjscfwJz94EuGOTE/QjZ73pgsSrnMGwLqpS0A81LCU=,iv:bR93Hytm1jUpO09j0K0T9s3MNKyd19+bhYBFCTNV57w=,tag:tNlXBixvDTw6XelAXgxREw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
