grafana:
    adminPassword: ENC[AES256_GCM,data:cXRzJYzr3cAA,iv:CRkHI8cWngURa8hL9JctKkqoYLsXba2ETGVM0I8d990=,tag:LCpj/q6K03CCPolFUhMU6Q==,type:str]
    ingress:
        tls:
            - hosts:
                - ENC[AES256_GCM,data:a3AaKn0UC2tNvhr7MLJ1FAVmgg==,iv:n5p4Ewpu4ESL1x0QaRD+JjlLOG10K1G1vWXIURGHAhw=,tag:DeqYKHD/KNCSvd/c9NH7EQ==,type:str]
        hosts:
            - ENC[AES256_GCM,data:GmRfxtfQGUCn9L+4gFxZEwQN4g==,iv:D6i3kjBsbM78F/RfTa5gU5BqEK1AaD27C+L6bUiC9bQ=,tag:ToLN3MD29wTVU2kgZNUeKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTkE3YlU1MVRMZ0hCWEIz
            UmlmWVplREYybGFzeTBlck9mVm9rdFV4NTNrCjdOc3hQVVRRUnVkVFF4RXJBUlpK
            KzdtbzBUQk45N1lPWTJwdk4yeDBUSW8KLS0tIE0wZ016UE5JbU1EeE5VYklPZDdV
            VVhSZHVTU29ydDhVTE85Nm0wcmtSREEKZV3/oPWIgLJ2pgDtYNW3w4b8B2x/Le/1
            B0mpI1dDKNwhX2lM/4Jgj28GGCybL2MsRH9Hu78t/7SZiZtGNq7nYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUHc2MnhDWWVxNFUrblZk
            bWU0NkFwMGx4cHdQS3RJNzhyQzZMV0w5cWtJCmROeld4Z1BiTmRKT0ZiYjZaVStX
            RHBHTGtSOFF2dC8weE5jekVma3FYRHMKLS0tIE85QXdRR2p2dFA5bmIyK3lpVjhB
            cm1SUTZ5TnFpTnlDYmNDL0RadTNJQVUKe3He78u0UqkPclym8CmgPpr7IrUqJvXn
            Jp161a1u+xQg1eKnGi9xfFrKqE0K2Rl2WDlPnuAclHmv8V1A8JlDRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-01T18:50:49Z"
    mac: ENC[AES256_GCM,data:EZ4/VHj3Ux2o8FmtL74YJdCsZSkHgx33yLAS3N0bVAAyjKW+WDAZzWy2oWqFb4kNRSuSUfDwqYCTxJKJqiyVUe7zpL9CmHYMp1xA0+aYSuajL5jLMwFeO86q+AlsZRpW4GehmwQF4/22fRrNCHhFgq5FBrEioGIJUE46LPHxoeI=,iv:0PxeljvZROe3hJnZXvultXfQCw37DxvajKnTBStFrIU=,tag:OFgs2/cnXGKJAxFWUoTyJw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
