env:
    pveAuthType: ENC[AES256_GCM,data:j3gbpIF1Jfo=,iv:Xa73twp3QhwWpEzL1BLc0MYTN3BCViQujc20iYcNN7Q=,tag:5/0medGjylHWatvhRJMYMg==,type:str]
    pvePassword: ENC[AES256_GCM,data:ezRNgIVNXel6c+0WjAKxrYWYQohP1kuZ,iv:Gsbu1xViyrVN2SZ+0ZMlIh/jLaXP40KNEw5sdIsZWXQ=,tag:uzHYA33srybce6vnEoMd2Q==,type:str]
    pveUser: ENC[AES256_GCM,data:M/d9CpFiWjloaYgW7OE=,iv:7DChF2bv9apmiOJ/SxXG/3KxWX4aCPN1SvirjkdDQCo=,tag:NJmWpEOFWoyFo9dWsQRebA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa0NRaEhKK1ZpUC96MUpM
            d2YwT2tzaGRUd3RnVVhtN0NHM1A0Yy9EeUdJCkJiQnBsVkgyRWhoVEFxaVIra1Vw
            eFRkZm5ocjZTT1JaQTRZNFZ6NFQrNUkKLS0tIFJPTURicHRWSU5GMlpicmZIYjhQ
            YnZ3N0RFVzF0ZTVqdmNma2gySUk4amcKIlleKSEYM3oQ7Glpjj0vIM5LRD8JUI8h
            SHQPKjznQz2CYQwig0nBUmwakNkDnCR5Wt4ErS2QHQjPjJ8tXEk/Xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MG5wUjJUK0NIRHgwdmZL
            TER2M0tXWlNuS25OcFlHMW9xaHQyRmYwb0NVCkxtc2xMdlRuZWRqRDZJZ3FsdS9O
            cGRxNHArZnpuV1Z5NnAyVXhuQ1dXM3cKLS0tIHQrVkk1cFVWUG5WeW5DSUl6YkhU
            YmFicTRMeXIySUZ0S2J5eVRuMktLU2sKbMDN6p3hprqyjaGthx3vJ3J+Ww6D5/KK
            FEt5IZT4aHzgrMDPHA5qes+s2FPdCX7J92CwEm3QeuSM8dcUeaJMoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8tzahcl0gfugsz2earwar3ga2rtqlgm9lrpc790ju06gzs633rqgn0366
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMzNLclhyV3d5bllDUHQv
            TGJpcVpvSEswa3dtWUJZUGgxZTJlOWNzN1JBCm9PVUVFQTZNcUQzMXExRllnbDhI
            TThSTFAvT2JxNkxLK1RiVWV6MFgrNDQKLS0tIHcvUjZjQWExQ1BmczB5dHFzZW5r
            MmtMZjhYREkzZ2ZsL2pvMUx6bXA5UEkKDmnTHeUbCI6FivYJ5QxvpPvrEkmWEqvI
            RdsqRXNN7XAZzBZ0UG+MliSLkopCdokwJ/p7o/fCgsdv89Fuqg6xrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12rh8n3qgq5k9jwwhhvrpmh4daahtjh3q28nm4pn5rwryvr4spg4qmadxxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTHZGekZSQkgrdEx0T2xQ
            d2ZJOXkrRTgzN01WdWpoOHdncllKZ08xSURZCmN4cmVZU01Wb1FLbGExamxkazNv
            c3ZuZXZzZWtKeW9RajZWTnM3UmZvR3cKLS0tIE1lMlBreXJmLzlqVitLVDlpZ3RF
            SmdXSlZXK1BOTCtyMzN6ZmxJOTZmVUUKTAbvXGctPZeDKTKjkvpo7O0FKiqW3BdM
            ghinldTo62q7M/6bSxE1zxZAxOpjIZJDkfZlxtyHwLXK4Nbbp07taA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T03:02:21Z"
    mac: ENC[AES256_GCM,data:E4p1M6aY9E9ZXMt6jzuwMkHPPBgYNZSGre7ZFuV8vshaOCZu1IMuLKjfdV4zgLL35EBJwFWfdaIgt50hmJwQAg/Egm+QpzwTGnpla+cgEqRBvwuXuXkpU1B3jrdxmC5DVCrr+r/HmqTbk7oGCNVX5eO/8+YmBgS96/6m5lJbMk4=,iv:VGGv5uzU36i7TOBOM3hMeG7W1ecbeJwJWc4iav4h810=,tag:zhWP1VF6pMDYsmbEjNIHPA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
