credentials:
    secretContents:
        cloud: ENC[AES256_GCM,data:sZOwBXQXrIUvTaV2vXTLkFvu3+h5tDcQPSXPv740RDDkOT3P88R84LVoh5JUCGDRe/rqbVoSG4sxmGSMZ/AIuO2HWWU1KTPdNvtKw/pxJcEIfCzlBMJSCkfhCKuNr+1Os5PlMa03mf6GN6fG,iv:Pv1qE+3U3e2PBlB2ghCHYRgnsHj45O+nL07j4FIxL+Q=,tag:vloCNN+AJLnHsryLs5wklQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTFFLSjNTQ1RINEJnTEo5
            MkhSdUIrMU1rcDE5WStKRTFjQzVaSkJDSzI0CjRRVG1aZjdFaXBFK050WlVERzVp
            TGtwZHorTXgvQmY2VmRVYm45TnlldGcKLS0tIE05eDNWZWQzU2VpSlZqRTBhMU9X
            YWFoelBram9keXF0YURLWUVIZThnNzgKgRjgzEmCeBoh4oWyAflDoGS4nKwkNVae
            Vr1zDK1x6SxR8eyglsleJL2njtCqb5KZR4TKtHisxh0p0fZ7XT/+YA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age197v79pan9he4xqku2z5uyz56n6628rrc739vjzzhz7xp2hukqvusrm7x26
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVkhsNjJxRlVUT1o0SHRQ
            blFodysxbm9WdGFXdEc0OHVtdm9wRWFZMkdVCk95TmdiZ24xSStOWFVURVZpdmZR
            d3lQdUtoZXpkbG5IRjNZWlNJYThqNXcKLS0tIE03aUJ3dFFtSkxicWFaMUtoNTVq
            QnlFaUVXUlpWeXE3WWhPUHc4WFZxTDgKvWkDOY/RjGDwv02IhI+fKr03JZX76JSJ
            JMcYIn5s4cC23YG0kXO4ozKyDeXpOciGQDEIUMcjSnQmbRW5ppIv0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f8tzahcl0gfugsz2earwar3ga2rtqlgm9lrpc790ju06gzs633rqgn0366
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VHdJV3ZSSjh3czJ4MWh5
            OWRXaFd6ekZuaXdGUU5RMWRTVG9ETHdsdGhVCkoxMFExSVZTSHh5MWIrSXFwSFBQ
            NEZod0ljZW1RSXpJWUY4L2NtUVRnL0kKLS0tIFBRVFBCM1FkekpHM3FranFTYWpM
            U3pvSk11dm5sNjEydGVha0U3OThxNncKgdUv4KdwgizH5QkDOo8jcztsIGNSlRm8
            2lA7UBmL276Dkko50H8Ojz30XyeuyIIztIu4OirlmzG0xMq3Z3F/DQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12rh8n3qgq5k9jwwhhvrpmh4daahtjh3q28nm4pn5rwryvr4spg4qmadxxn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cjdOL2dPLzVsYTh2Y3RR
            RkxXbUhYajJtQ3EyWVZEUWxuUkJuSE9nZTFFCmhSZ3VyTzdpa0c5ZFp2R1lKb1V5
            SFR1bE0vNTNDMmN6SnVkSkk5WCtvNlEKLS0tIG1XYmlUQXcwU2JuRHNFK010S2xN
            L2lnTGJoQXhJMXU0MTNCdG9EQ1BWeXcKGdsHGPoW0TQ4Yrln0iJnxtLrkId+dviV
            IHvaYd9iG61qJAGcV24mohKoE07tZWqrt8/jg5mXKSIntpOCVA0vGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T03:02:21Z"
    mac: ENC[AES256_GCM,data:3z/LuolR+GEt/FeJM4R1F+yWkYYe8rVo1Nu9J8WS03L9CvidL+yl254Uo6IVuDHXeYy4scdq0QdFqcx98A7znpgs5ycHe0X4a/dMML5vIHa2TZhnf5qz8MyBbnWygvqUwv2rD8RX2AzsprvOWxuEfdGscezW23jQjsjXcd3MeOc=,iv:vo9QE/ZhRxCtMjF/u2ujaA0Url6uUQmMhPGIKhRQWOg=,tag:F80MAUc/BLQYqyoF83uMgw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
