initContainers:
    - name: ENC[AES256_GCM,data:GHJpU03VmTobNjNjSX+JnDev3ixc,iv:xURL9ofRrOzyQaPzbx4rkkHecuMSQ8q9nsdhNoOVILI=,tag:ZwWS0F5wg/k9kY0GU0WiYg==,type:str]
      image: ENC[AES256_GCM,data:z6N/V487SIJTZQwrC7sgk59Q72y8+L16S2bxpvr6wENtJYU=,iv:d8yRIbc/8cfOVrv5TpKQYvto/MA5bK4l1OfpjGvZLbM=,tag:9uXtKAysesp2U8XT+72LNA==,type:str]
      imagePullPolicy: ENC[AES256_GCM,data:5cHgvMRGpCGC0Tt9,iv:yJGKpdensx+sCL+pdkF9HN02e0sjTRhFrBLCIAAdrCY=,tag:g1KSYLhS3GYhDI6uteGVmg==,type:str]
      volumeMounts:
        - mountPath: ENC[AES256_GCM,data:GqifYNNpuA==,iv:0AojTUeRDAyhOWINLzX2rSNGx1659G8o7bSKblaCwn8=,tag:YseSeDwkV6kkXMwTUrcwSw==,type:str]
          name: ENC[AES256_GCM,data:1Iwz5FzL7Q==,iv:q3NufWilDSG/1NzWrBMsoTzdq3PrOTKyi/vh+Qc3IOg=,tag:AMpDOb4si29Y5KgnbH4HKw==,type:str]
    - name: ENC[AES256_GCM,data:FHSn02yhz5ayJneLcZD3HERKTd9X,iv:GoJsI0mlH5IEGPXAkZE8yZc9F4j8iDh5RJvyUEAmSyc=,tag:ZBqWR9GorOjuyx7lMiTdlQ==,type:str]
      image: ENC[AES256_GCM,data:mdmepAruAt/YVYriPyWurGdkzyZzcBWniqT02WgDsMkdfZw=,iv:YR8o8Nq8T+YalQEXWvMZ56P5B8G61hzdI41Ei1oBvI0=,tag:d7FlX/Jjyu2ICKPkdBgCxw==,type:str]
      imagePullPolicy: ENC[AES256_GCM,data:5cHgvMRGpCGC0Tt9,iv:yJGKpdensx+sCL+pdkF9HN02e0sjTRhFrBLCIAAdrCY=,tag:g1KSYLhS3GYhDI6uteGVmg==,type:str]
      volumeMounts:
        - mountPath: ENC[AES256_GCM,data:GqifYNNpuA==,iv:0AojTUeRDAyhOWINLzX2rSNGx1659G8o7bSKblaCwn8=,tag:YseSeDwkV6kkXMwTUrcwSw==,type:str]
          name: ENC[AES256_GCM,data:1Iwz5FzL7Q==,iv:q3NufWilDSG/1NzWrBMsoTzdq3PrOTKyi/vh+Qc3IOg=,tag:AMpDOb4si29Y5KgnbH4HKw==,type:str]
configuration:
    backupStorageLocation:
        - provider: ENC[AES256_GCM,data:ni7b,iv:fedesOR3hHlQ42XcCRlh8EbNPmtJOJy5ZsT9MRBv7xQ=,tag:cVg4Szq4Q09+3U1mldNV6Q==,type:str]
          bucket: ENC[AES256_GCM,data:+ywdvJerXCMmO7+PoAHYTeLaZOO/Q7ZQbUHG7w==,iv:ykOCxxyJTB1RLBFJXqXA+gqmdUVLbrk9qBV67RFD4Qk=,tag:gUkocX3gRYUkffPkysuCzQ==,type:str]
          config:
            region: ENC[AES256_GCM,data:M9Ul0Rxb1Q==,iv:KhqU7FLM/nhQdkShwc2d8KnbQcf5flKDLLfUHPMoCOE=,tag:d8XuHJuVxzI58HtesKeCMA==,type:str]
            s3ForcePathStyle: ENC[AES256_GCM,data:u8LyKg==,iv:xWp4oiA5/UD+x0YqlI4TFTBMw3vwFM7Ng/V+Bqqzj8U=,tag:T8fgJdSB5+ksn2dlP5NXQQ==,type:bool]
            s3Url: ENC[AES256_GCM,data:IEo7yxGmGrI+dFzX57MXo+JtWY9fVUu51nme6vkSbeAHmPoATrE=,iv:Opo29Xi9vIYz2Tp9g+cX1N13dIvuv1ZZp3z5OQ27Y2U=,tag:WVTx1tHKUICm67edPT9eLw==,type:str]
    volumeSnapshotLocation:
        - provider: ENC[AES256_GCM,data:WHla36z7cCornlhkgyqC,iv:NDauT1iuiLZCZux5HWlT7uRnKTOO9icOdXG/fRvSiYs=,tag:0IHVtk4ZoegQlSHbRwm4bg==,type:str]
credentials:
    secretContents:
        cloud: ENC[AES256_GCM,data:LNeOHk8GkgC9LF8lkS3WPhwFqthdyFLcWuCjTh88kU0eic9Z0BG93Lx0nSbOzaI3FC/9tyxPWoIAIpnuGcAP14vmZpJpasd+CdBbI6CL/QRr4N1OHpit39YhfQijmqZTf6Fo9SCxgYV6GYmi,iv:w7eJKptdJgSjgq7ZVdRn+bG/fi4HGgipOKtNetwf1Mk=,tag:dDJLVpyWtv04MOU8LnrKlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mz9l2esa3xvvpzpf8dgccmh3v9573gjpyhfc6hspxrr86mg3rgzq589yhy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVDhrZWtFOUh6enErbWU0
            cWM5dkcrSENnRk9Ja040VWpaanltZ2Rrb0RBCkVUNjVlOXhJeS8wTEN1K09rcnpX
            aVFldzgyV0FqTnVqSi90alNmc2RRT2MKLS0tIDMxeDhJSjgwV1BiZXhpSjV2aEEr
            TXE0ZW1uY1RsdFliL2QrTVR0UGtXR0EKSin176rhaWQRm1CXSXcj/x4qTomdQyxF
            cee0JJsgrltjDPnGX+Li9TkycPC+gSR1zsKU2ItUekHrQv7lsLxXNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-28T03:20:03Z"
    mac: ENC[AES256_GCM,data:2BwSiYKn/Ylwu7IHp28obItiJrdFET6coHa5pAmF35JwaSW6MgaHOwViVWIXuOMUes8IDTMeof3wN5JeE2FROrMv+gqJQt06DYVmGbQXGprg1V6FIPirPaTvL+2eqop8JSLsBgWoIyoYzb0svhcMW9WIY51kY/I8KvgoGd5PdNQ=,iv:9XZjSp2OBkmdM3KFE5vXiBqIYs5eMl9ksz4Zuu1u8OY=,tag:T7EN+RQshWEgCDdCMyX1QA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
