# TODO: before using this, enable sops or git-crypt
#
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
# some_password: welcome
