apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
  labels:
    app: "{{ .Chart.Name }}"
data:
  mosquitto.conf: |-
    listener {{ .Values.container.port }} 0.0.0.0
    protocol mqtt

    # we are not going to add an ingress, so this is ok.
    # anyone inside the cluster could snoop on the nginx
    # proxy traffic anyway and just grab the creds.
    # If the cluster is ever hardened, eg. with ipsec between
    # nodes, then revisit this.
    allow_anonymous true
