apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-mqtt
  labels:
    app: moquitto-mqtt
data:
  mosquitto.conf: |-
    listener 1883 0.0.0.0
    protocol mqtt

    # FIXME: enable auth. This din't work by itself, but acls might be needed
    allow_anonymous true
    #password_file /mosquitto/config/passwords.conf
