apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-mqtt
  labels:
    app: moquitto-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-mqtt
  template:
    metadata:
      labels:
        app: mosquitto-mqtt
    spec:
      containers:
        - name: mosquitto-mqtt
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          ports:
            - name: mqtt
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
            - name: secrets
              mountPath: /mosquitto/config/passwords.conf
              subPath: passwords.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: mosquitto-mqtt
        - name: secrets
          secret:
            secretName: mosquitto-mqtt
