apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    app: mosquitto-mqtt
