apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt
spec:
  type: LoadBalancer
  LoadBlancerIP: 192.168.10.51
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    app: mosquitto-mqtt
