releases:
  #
  # Docker registry
  #
  - name: docker-registry
    namespace: docker-registry
    chart: twuni/docker-registry
    version: 2.2.2
    wait: true
    values:
      - ../values/docker-registry.yaml
    secrets:
      - ../secrets/docker-registry.yaml
