releases:
  # prometheus
  #
  # see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
  # for cleanup
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 54.1.0
    values:
      - ../values/prometheus.yaml
    secrets:
      - ../secrets/prometheus.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "../manifests/monitoring/"]

  #
  # loki
  #
  - name: loki-stack
    namespace: logging
    chart: grafana/loki-stack
    version: 2.9.11
    values:
      - ../values/loki-stack.yaml

  #
  # prometheus-pve-exporter
  #
  - name: prometheus-pve-exporter
    namespace: monitoring
    chart: christianknell/prometheus-pve-exporter
    version: 1.2.1
    values:
      - ../values/prometheus-pve-exporter.yaml
    secrets:
      - ../secrets/prometheus-pve-exporter.yaml
