releases:
  #
  # mosquitto-mqtt
  #
  - name: mosquitto-mqtt
    namespace: home-automation
    chart: ../charts/mosquitto-mqtt
    version: 1.0.0
    set:
      - name: installCRDs
        value: true
    values:
      - ../values/mosquitto-mqtt.yaml
    secrets:
      - ../secrets/mosquitto-mqtt.yaml

  #
  # zigbee2mqtt
  #
  - name: zigbee2mqtt
    namespace: home-automation
    chart: ../charts/zigbee2mqtt
    version: 1.0.0
    needs:
      - home-automation/mosquitto-mqtt

  #
  # home-assistant
  #
  - name: home-assistant
    namespace: home-automation
    chart: ../charts/home-assistant
    version: 1.0.0
    values:
      - ../values/home-assistant.yaml
    secrets:
      - ../secrets/common.yaml

  #
  # appdaemon
  #
  # I hate that ha can't programatically create users or access
  # tokens via commands or injected config. Because of that,
  # we have to first login and and then get an access token for
  # them and save it into secrets/appdaemon.yaml under the
  # key
  #   home-assistant:
  #     token: "<the token from ha>"
  # then re-run helmfile apply. Without the token, this chart
  # won't create the deployment
  - name: appdaemon
    namespace: home-automation
    chart: ../charts/appdaemon
    version: 1.0.0
    secrets:
      - ../secrets/appdaemon.yaml
