releases:
  #
  # paperless-ngx
  #
  - name: paperless-ngx
    namespace: paperless-ngx
    chart: gabe565/paperless-ngx
    version: 0.9.2
    secrets:
      - ../secrets/paperless-ngx.yaml
    values:
      - ../values/paperless-ngx.yaml

  #
  # immich
  #
  - name: immich
    namespace: immich
    chart: immich/immich
    version: 0.3.0
    secrets:
      - ../secrets/immich.yaml
    values:
      - ../values/immich.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-f", "../manifests/immich/"]

  #
  # tandoor
  #
  - name: tandoor
    namespace: tandoor
    chart: gabe565/tandoor
    version: 0.8.11
    secrets:
      - ../secrets/tandoor.yaml
    values:
      - ../values/tandoor.yaml
