apiVersion: v1
kind: Service
metadata:
  name: external-node-exporter
  namespace: monitoring
  labels:
    name: external-node-exporter
    release: kube-prometheus-stack
    jobLabel: node-exporter
spec:
  ports:
    - name: http-metrics
      port: 9100
      protocol: TCP
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-node-exporter
  namespace: monitoring
  labels:
    name: external-node-exporter
    release: kube-prometheus-stack
    jobLabel: node-exporter
subsets:
  # TODO: templatize these
  - addresses:
      - ip: 192.168.10.11
        nodeName: pve-01
      - ip: 192.168.10.12
        nodeName: pve-02
      - ip: 192.168.10.13
        nodeName: pve-03
      - ip: 192.168.10.14
        nodeName: pve-04
      - ip: 192.168.10.15
        nodeName: pve-nas-01
    ports:
      - name: http-metrics
        port: 9100
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-node-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    jobLabel: node-exporter
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      name: external-node-exporter
  endpoints:
    - port: http-metrics
