apiVersion: v1
data:
  loki.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      uid: loki
      url: http://loki-stack.logging.svc.cluster.local:3100
      access: proxy
      isDefault: false
kind: ConfigMap
metadata:
  name: stable-kube-prometheus-sta-grafana-loki-datasource
  namespace: monitoring
  annotations:
    meta.helm.sh/release-name: stable
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: stable
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    grafana_datasource: "1"
    heritage: Helm
    release: stable
