# TODO: replace domain with a variable
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-blinkies.io
  namespace: ingress-nginx
spec:
  secretName: wildcard-blinkies.io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.blinkies.io"
