nfs_pv:
  server: nas-01
  path: /storage/media
  capacity: 256Gi

jellyfin:
  image:
    repository: jellyfin/jellyfin
    tag: 10.9.9

  persistence:
    config:
      enabled: true
      size: 100Gi
    media:
      enabled: true
      existingClaim: jellyfin-nfs-pvc
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
