image:
  repository: acockburn/appdaemon
  tag: 4.4.2
  pullPolicy: IfNotPresent

container:
  port: 5050

service:
  type: ClusterIP
  targetPort: 5050
  port: 5050

persistence:
  size: 1Gi

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: "500m"
    memory: 512Mi

homeassistant:
  url: "http://home-assistant:8123"
  token: ""

timezone: "America/Los_Angeles"
latitude: 0
longitude: 0
elevation: 30
