apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    homeassistant:
      latitude: {{ .Values.latitude }}
      longitude: {{ .Values.longitude }}
      elevation: {{ .Values.elevation }}
      time_zone: {{ .Values.time_zone }}
      unit_system: us_customary
      currency: USD
      country: US

    http:
      use_x_forwarded_for: true
      trusted_proxies: {{ .Values.configuration.trusted_proxies }}

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: []
    group:
    script:

    lutron_caseta:
      - host: {{ .Values.configuration.lutron_ip }}
        keyfile: caseta.key
        certfile: caseta.crt
        ca_certs: caseta-bridge.crt

    light:
      - platform: group
        name: "Common Lights"
        entities:
          - light.dining_room_chandelier
          - light.ames_light
          - light.nook_light
          - light.ram_light

    scene:
      - name: Kitchen Night
        icon: "mdi:lightbulb-night"
        entities:
          light.kitchen_ceiling_lights:
            state: "on"
            brightness: 75

      - name: TV Time Playing
        icon: "mdi:lightbulb-night"
        entities:
          light.ames_light:
            state: "on"
            brightness: 75
          light.ram_light:
            state: "off"
          light.main_bedroom_ceiling_lights:
            state: "off"
          light.hallway_main_lights:
            state: "off"
          light.kitchen_ceiling_lights:
            state: "off"
          light.dining_room_chandelier:
            state: "off"
          light.nook_light:
            state: "off"

      - name: TV Time Paused
        icon: "mdi:lightbulb-night"
        entities:
          light.ames_light:
            state: "on"
            brightness: 75
          light.kitchen_ceiling_lights:
            state: "on"
            brightness: 75

    input_boolean:
      goodnight_mode:
        name: Goodnight Mode
        initial: off
        icon: mdi:toggle-switch

      tv_time_mode:
        name: TV Time Mode
        initial: off
        icon: mdi:toggle-switch

      {{ if .Values.configuration.include_fakes }}
      fake_motion:
        name: Fake Motion
        initial: off
        icon: mdi:motion-sensor

      fake_light:
        name: Fake Light
        initial: off
        icon: mdi:lightbulb

      fake_night_light:
        name: Fake Night Light
        initial: off
        icon: mdi:lightbulb
      {{ end }}
  caseta.key: |-
    {{ .Values.lutron.caseta_key | nindent 4 | trim }}
  caseta.crt: |-
    {{ .Values.lutron.caseta_crt | nindent 4 | trim }}
  caseta-bridge.crt: |-
    {{ .Values.lutron.caseta_bridge_crt | nindent 4 | trim }}
