apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
data:
  # TODO: pass in lat/long here
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies: {{ .Values.configuration.trusted_proxies }}

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: []
    group:
    script:
    scene:

    input_boolean:
      goodnight_mode:
        name: Goodnight Mode
        initial: off
        icon: mdi:toggle-switch

      {{ if .Values.configuration.include_fakes }}
      fake_motion:
        name: Fake Motion
        initial: off
        icon: mdi:motion-sensor

      fake_light:
        name: Fake Light
        initial: off
        icon: mdi:lightbulb

      fake_night_light:
        name: Fake Night Light
        initial: off
        icon: mdi:lightbulb
      {{ end }}
