apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # TODO: pass this in
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: []
    group:
    script:
    scene:

    input_boolean:
      goodnight_mode:
        name: Goodnight Mode
        initial: off
        icon: mdi:toggle-switch

      fake_light:
        name: Fake Light
        initial: off
        icon: mdi:lightbulb

      fake_night_light:
        name: Fake Night Light
        initial: off
        icon: mdi:lightbulb
