apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: TZ
              value: {{ .Values.time_zone }}
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - name: persistent-storage
              mountPath: /config
            - name: config-volume
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
            - name: config-volume
              mountPath: /config/caseta.key
              subPath: caseta.key
            - name: config-volume
              mountPath: /config/caseta.crt
              subPath: caseta.crt
            - name: config-volume
              mountPath: /config/caseta-bridge.crt
              subPath: caseta-bridge.crt
      volumes:
        - name: config-volume
          configMap:
            name: "{{ .Chart.Name }}-config"
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-pvc"
