apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
spec:
  accessModes:
    - "{{ .Values.persistence.accessMode }}"
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
  storageClassName: "{{ .Values.persistence.storageClassName }}"
  persistentVolumeReclaimPolicy: Retain
