apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8123
      protocol: TCP
  selector:
    app: home-assistant
