image:
  repository: koenkk/zigbee2mqtt
  tag: latest
  pullPolicy: IfNotPresent

container:
  port: 8080

service:
  type: ClusterIP
  targetPort: 8080
  port: 8080

persistence:
  size: 100Mi

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: "500m"
    memory: 512Mi

mqtt_server: "mqtt://mosquitto-mqtt:1883"
serial_port: "/dev/ttyACM0"

domain: .home.arpa
hostname: zigbee2mqtt
