image:
  repository: homeassistant/home-assistant
  tag: stable
  pullPolicy: IfNotPresent

container:
  port: 8123

service:
  type: ClusterIP
  port: 8123

persistence:
  size: 5Gi

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: "500m"
    memory: 512Mi

configuration:
  trusted_proxies:
    - 10.42.0.0/16
  include_fakes: true

domain: .home.arpa
hostname: ha
