apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.accessKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secretKey | b64enc | quote }}
  AWS_ENDPOINTS: {{ .Values.endpoint | b64enc | quote }}
  AWS_REGION: {{ .Values.region | b64enc | quote }}
